/* -------------------------------------------------------------------------- */
/*                             Creator management                             */
/* -------------------------------------------------------------------------- */
# LogIn
### correct login
POST http://localhost:3001/api/sessions
Content-Type: application/json

{"username": "John",
 "password": "867AWkAVpmshDFj&"}

### wrong username pwd
POST http://localhost:3001/api/sessions
Content-Type: application/json

{"username": "John",
 "password": "MNM4H3"}

### missing credentials
POST http://localhost:3001/api/sessions

# getUserInfo
### check whether the creator is logged in or not
GET http://localhost:3001/api/sessions/current

# logOut
###logOut
DELETE http://localhost:3001/api/sessions/current

/* -------------------------------------------------------------------------- */
/*                     BackgroundImages management                            */
/* -------------------------------------------------------------------------- */
### List BackgroundImages
GET http://localhost:3001/api/backgroundImages

/* -------------------------------------------------------------------------- */
/*                              Memes management                              */
/* -------------------------------------------------------------------------- */
### List Memes
GET http://localhost:3001/api/memes

### List Public Memes
GET http://localhost:3001/api/memes/public

# Create a Meme
### Ok
POST http://localhost:3001/api/memes
Content-Type: application/json

{"imageId":2,
"title":"This project",
"isProtected":true,
"fontFamily":"Arial",
"fontSize":40,
"color":"black",
"sentences":["Do the bare minimum requirements",
"Add 300 customized styles to make it \"just right\"",
null],
"originalCreatorId":1,
"originalIsProtected":true}

### ImageId not existent/not int (foreign key constraint failed)
POST http://localhost:3001/api/memes
Content-Type: application/json

{"imageId":45,
"title":"This project",
"isProtected":true,
"fontFamily":"Arial",
"fontSize":40,
"color":"black",
"sentences":["Do the bare minimum requirements",
"Add 300 customized styles to make it \"just right\"",
null],
"originalCreatorId":1,
"originalIsProtected":true}

### empty/null title 
POST http://localhost:3001/api/memes
Content-Type: application/json

{"imageId":2,
"title":"",
"isProtected":true,
"fontFamily":"Arial",
"fontSize":40,
"color":"black",
"sentences":["Do the bare minimum requirements",
"Add 300 customized styles to make it \"just right\"",
null],
"originalCreatorId":1,
"originalIsProtected":true}

### wrong type title OK
POST http://localhost:3001/api/memes
Content-Type: application/json

{"imageId":2,
"title":34.5,
"isProtected":"cuisd",
"fontFamily":"Arial",
"fontSize":40,
"color":"black",
"sentences":["Do the bare minimum requirements",
"Add 300 customized styles to make it \"just right\"",
null],
"originalCreatorId":1,
"originalIsProtected":true}

### isProtected not boolean
POST http://localhost:3001/api/memes
Content-Type: application/json

{"imageId":2,
"title":34.5,
"isProtected":"cuisd",
"fontFamily":"Arial",
"fontSize":40,
"color":"black",
"sentences":["Do the bare minimum requirements",
"Add 300 customized styles to make it \"just right\"",
null],
"originalCreatorId":1,
"originalIsProtected":true}

### not supported fontFamily
POST http://localhost:3001/api/memes
Content-Type: application/json

{"imageId":2,
"title":34.5,
"isProtected":1,
"fontFamily":"fhdguid",
"fontSize":40,
"color":"black",
"sentences":["Do the bare minimum requirements",
"Add 300 customized styles to make it \"just right\"",
null],
"originalCreatorId":1,
"originalIsProtected":true}

### not supported fontSize
POST http://localhost:3001/api/memes
Content-Type: application/json

{"imageId":2,
"title":"This project",
"isProtected":true,
"fontFamily":"Arial",
"fontSize":155000,
"color":"black",
"sentences":["Do the bare minimum requirements",
"Add 300 customized styles to make it \"just right\"",
null],
"originalCreatorId":1,
"originalIsProtected":true}

### not supported color
POST http://localhost:3001/api/memes
Content-Type: application/json

{"imageId":2,
"title":"This project",
"isProtected":true,
"fontFamily":"Arial",
"fontSize":40,
"color":"fdshjkfhsdk",
"sentences":["Do the bare minimum requirements",
"Add 300 customized styles to make it \"just right\"",
null],
"originalCreatorId":1,
"originalIsProtected":true}

### wrong type creatorId
POST http://localhost:3001/api/memes
Content-Type: application/json

{"imageId":2,
"title":"This project",
"isProtected":true,
"fontFamily":"Arial",
"fontSize":40,
"color":"black",
"sentences":["Do the bare minimum requirements",
"Add 300 customized styles to make it \"just right\"",
null],
"originalCreatorId":"fhduis",
"originalIsProtected":true}

### wrong type originalIsProtected
POST http://localhost:3001/api/memes
Content-Type: application/json

{"imageId":2,
"title":"This project",
"isProtected":true,
"fontFamily":"Arial",
"fontSize":40,
"color":"black",
"sentences":["Do the bare minimum requirements",
"Add 300 customized styles to make it \"just right\"",
null],
"originalCreatorId":1,
"originalIsProtected":"fjdios"}

### protected meme can't become public
POST http://localhost:3001/api/memes
Content-Type: application/json

{"imageId":2,
"title":"This project",
"isProtected":false,
"fontFamily":"Arial",
"fontSize":40,
"color":"black",
"sentences":["Do the bare minimum requirements",
"Add 300 customized styles to make it \"just right\"",
null],
"originalCreatorId":2,
"originalIsProtected":true}

### multiple errors
POST http://localhost:3001/api/memes
Content-Type: application/json

{"imageId":2,
"title":"This project",
"isProtected":true,
"fontFamily":"Arial",
"fontSize":40,
"color":"black",
"sentences":["",
"",
null],
"originalCreatorId":1,
"originalIsProtected":"fdsjkl"}

### multiple errors
POST http://localhost:3001/api/memes
Content-Type: application/json

# Delete a Meme
### OK
DELETE http://localhost:3001/api/memes/24

### Not present
DELETE http://localhost:3001/api/memes/99

### Not mine
DELETE http://localhost:3001/api/memes/4